project_id = "dpybiegurkiqwponvxac"

[global.env]
SUPABASE_URL = "env"
SUPABASE_SERVICE_ROLE_KEY = "env"

[[log-transaction]]
name = "log-transaction"
path = "/log-transaction"
verify_jwt = false

[[wallet-auth]]
name = "wallet-auth"
path = "/wallet-auth"
verify_jwt = false